<?xml version="1.0" encoding="utf-8"?>
<Database Name="LIFENAV" Class="ClientDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PPC-25970\SQLEXPRESS;Initial Catalog=LIFENAV;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LocalConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LIFENAV_Client" Member="LIFENAV_Clients">
    <Type Name="LIFENAV_Client">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address1" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="City" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StateCode" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="ZipCode" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="HomePhone" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="WorkPhone" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Column Name="CreationDate" AutoSync="Never" Type="System.DateTime" DbType="DateTime NOT NULL" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.LIFENAV_GetMembershipXML" Method="LIFENAV_GetMembershipXML">
    <Parameter Name="clientId" Type="System.Int32" DbType="Int" />
    <ElementType Name="LIFENAV_GetMembershipXMLResult">
      <Column Name="Column1" Type="System.Xml.Linq.XElement" DbType="Xml" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>