<?xml version="1.0" encoding="utf-8"?>
<Database Name="LIFENAV" Class="ScheduleDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=PPC-25970\SQLEXPRESS;Initial Catalog=LIFENAV;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="LIFENAVConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.LIFENAV_ScheduleView" Member="LIFENAV_ScheduleViews">
    <Type Name="LIFENAV_ScheduleView">
      <Column Name="ClientId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServiceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServiceName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReservedDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Status" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.LIFENAV_GetDailyAppointments" Method="LIFENAV_GetDailyAppointments">
    <Parameter Name="startDate" Type="System.DateTime" DbType="DateTime" />
    <Parameter Name="duration" Type="System.Int32" DbType="Int" />
    <Parameter Name="clientId" Type="System.Int32" DbType="Int" />
    <ElementType Name="LIFENAV_GetDailyAppointmentsResult">
      <Column Name="ClientId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServiceId" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ServiceName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ShortName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ReservedDateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.LIFENAV_GetMonthlySchedule" Method="LIFENAV_GetMonthlySchedule">
    <Parameter Name="startDate" Type="System.DateTime" DbType="DateTime" />
    <ElementType Name="LIFENAV_GetMonthlyScheduleResult">
      <Column Name="Year" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Month" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Day" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Appointments" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>